### ISSUE TITLE
Proper way to define the module

### ISSUE THREAD

**Issue by fourpixels** [primus/eventemitter3#49] opened 2016-02-25 08:49 UTC
Hi guys,
Can we please include a proper way to define the module, so it actually starts working everywhere? Something like:

``` js
(function (name, definition){
    if (typeof define === 'function'){ // AMD
        define(definition);
    } else if (typeof module !== 'undefined' && module.exports) { // Node.js
        module.exports = definition(require);
    } else { // Browser
        var theModule = definition(), global = this, old = global[name];
        theModule.noConflict = function () {
            global[name] = old;
            return theModule;
        };
        global[name] = theModule;
    }
})('EventEmitter3', function (require, exports, module) {
    // the real code here
});
```

Right now I **cannot** use it withing AMD environment, which is a total shame!

If you don't like it - just tweak the code a little, like not adding it to the global scope if it's for the browser, and just return the newly defined "module", so that very simple and basic usage can be achieved with no pollution at all.

**Comment by lpinca** [comment] 2016-02-25 10:10
Possible duplicate of #36, #30, #22.

**Comment by fourpixels** [comment] 2016-02-25 11:33
Well no, because @3rd-Eden added https://github.com/primus/eventemitter3/commit/b59a4cc67c8f2d7542465104b37ba48bff7d65c7
Module check **is there**, but this is not AMD module, rather than node-style module export.

**Comment by lpinca** [comment] 2016-02-25 11:43
Linking @jcrugzz's [comment](https://github.com/primus/eventemitter3/issues/30#issuecomment-95678974) in #30.

**Comment by lpinca** [comment] 2017-03-31 06:30
Closing this, please comment or reopen if needed.

**Closed by lpinca** 2017-03-31 06:30 UTC
